version: 2.1
jobs:
   build:
      docker:
         - image: ankur9718/zmcase2:latest
      steps:
         - checkout
        
         - run:
            git config --global url."https://$${GITHUB_ACCESS_TOKEN}:@github.com/".insteadOf https://github.com/
                                
         - run:
            git clone https://github.com/Zimbra/zm-cicd.git
         - run:
            command: |
               if [ $? -eq 0 ]
               then
                 echo "config files changed"
               fi
